/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/wrangler.jsonc --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: f36252721b0d9a8dbbe94f840883a763)
interface __BaseEnv_Env {
	ARCHIVE: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "preview" | "production";
	ALLOWED_ORIGINS: "https://satellite.agentba.se,https://satellite-rho.vercel.app";
	UPSTREAM_PROXY_URL: "https://satellite.agentba.se/api/signals?upstream=1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./data-worker");
	}
	interface PreviewEnv {
		ARCHIVE: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "preview";
		ALLOWED_ORIGINS: "https://satellite.agentba.se,https://satellite-rho.vercel.app";
		UPSTREAM_PROXY_URL: "https://satellite.agentba.se/api/signals?upstream=1";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_ORIGINS" | "UPSTREAM_PROXY_URL">> {}
}
